<?xml version="1.0" ?>
<robot name="blindbot" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find blindbot_description)/urdf/common_properties.xacro"/>
  <xacro:include filename="$(find blindbot_description)/urdf/blind_asus_bot.gazebo.xacro"/>

  <xacro:property name="asus_cam_rgb_px" value="0.005"/>
  <xacro:property name="asus_cam_rgb_py" value="0.023"/>
  <xacro:property name="asus_cam_rgb_pz" value="0.02"/>
  <xacro:property name="asus_cam_depth_offset" value="0.015"/>

  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link" />
    <origin xyz="0 0 0.010" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <pose>0 0 0 0 0 0</pose>

    <visual>
      <origin xyz="-0.064 0 0.0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://blindbot_description/meshes/bases/waffle_base.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="light_black"/>
    </visual>

    <collision name="base">
      <origin xyz="-0.064 0 0.047" rpy="0 0 0"/>
      <geometry>
        <box size="0.266 0.266 0.094"/>
      </geometry>
      <max_contacts>10</max_contacts>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1.3729096e+00"/>
      <inertia ixx="8.7002718e-03" ixy="-4.7576583e-05" ixz="1.1160499e-04"
               iyy="8.6195418e-03" iyz="-3.5422299e-06"
               izz="1.4612727e-02" />
    </inertial>
  </link>

  <joint name="wheel_left_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_left_link"/>
    <origin xyz="0.0 0.144 0.023" rpy="-1.57 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="wheel_left_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="package://blindbot_description/meshes/wheels/left_tire.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.018" radius="0.033"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="2.8498940e-02" />
      <inertia ixx="1.1175580e-05" ixy="-4.2369783e-11" ixz="-5.9381719e-09"
               iyy="1.1192413e-05" iyz="-1.4400107e-11"
               izz="2.0712558e-05" />
      </inertial>
  </link>

  <joint name="wheel_right_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_right_link"/>
    <origin xyz="0.0 -0.144 0.023" rpy="-1.57 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="wheel_right_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="package://blindbot_description/meshes/wheels/right_tire.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.018" radius="0.033"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="2.8498940e-02" />
      <inertia ixx="1.1175580e-05" ixy="-4.2369783e-11" ixz="-5.9381719e-09"
               iyy="1.1192413e-05" iyz="-1.4400107e-11"
               izz="2.0712558e-05" />
      </inertial>
  </link>

  <joint name="caster_back_right_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_back_right_link"/>
    <origin xyz="-0.177 -0.064 -0.004" rpy="-1.57 0 0"/>
  </joint>

  <link name="caster_back_right_link">
    <collision>
      <origin xyz="0 0.001 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.030 0.009 0.020"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.005" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>

  <joint name="caster_back_left_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_back_left_link"/>
    <origin xyz="-0.177 0.064 -0.004" rpy="-1.57 0 0"/>
  </joint>

  <link name="caster_back_left_link">
    <collision>
      <origin xyz="0 0.001 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.030 0.009 0.020"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.005" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>

  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0.0 0 0.000" rpy="0 0 0"/>
  </joint>

  <link name="imu_link"/>

  <joint name="scan_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_scan"/>
    <origin xyz="-0.064 0 0.122" rpy="0 0 0"/>
  </joint>

    <joint name="cliff_sensor_left_joint" type="fixed">
      <origin xyz="0.03 0.13601 0.0214" rpy="0 ${M_PI/2} 0" />
      <parent link="base_link"/>
      <child link="cliff_sensor_left_link" />
    </joint>
    <link name="cliff_sensor_left_link">
      <inertial>
        <mass value="0.0001" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                 iyy="0.0001" iyz="0.0"
                 izz="0.0001" />
      </inertial>
    </link>

    <joint name="cliff_sensor_right_joint" type="fixed">
      <origin xyz="0.03 -0.13601 0.0214" rpy="0 ${M_PI/2} 0" />
      <parent link="base_link"/>
      <child link="cliff_sensor_right_link" />
    </joint>
    <link name="cliff_sensor_right_link">
      <inertial>
        <mass value="0.0001" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                 iyy="0.0001" iyz="0.0"
                 izz="0.0001" />
      </inertial>
    </link>

    <joint name="cliff_sensor_front_joint" type="fixed">
      <origin xyz="0.07 0.00 0.0214" rpy="0 ${M_PI/2} 0" />
      <parent link="base_link"/>
      <child link="cliff_sensor_front_link" />
    </joint>
    <link name="cliff_sensor_front_link">
      <inertial>
        <mass value="0.0001" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                 iyy="0.0001" iyz="0.0"
                 izz="0.0001" />
      </inertial>
    </link>

  <link name="base_scan">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://blindbot_description/meshes/sensors/lds.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0.015 0 -0.0065" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.0315" radius="0.055"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.114" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>

<joint name="head_joint" type="fixed">
  <origin xyz="0.00 0.012 1.76" rpy="0 0 0"/>
  <parent link="base_link"/>
  <child link="head_link"/>
</joint>

<link name="head_link">
  <origin xyz="0 0 0" rpy="0 0 0"/>

  <!-- This inertial field needs doesn't contain reliable data!! -->
  <inertial>
    <mass value="0.0001" /> <!-- 0.564 -->
    <origin xyz="0 0 0" />
    <inertia ixx="0.05" ixy="0.0" ixz="0.0"
             iyy="0.05" iyz="0.0"
             izz="0.05" />
  </inertial>
</link>

  <!-- <joint name="camera_joint" type="continuous">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="head_link"/>
    <child link="camera_link"/>
    <axis xyz="0 1 0"/>
  </joint> -->

  <link name="camera_psi_link">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <inertial>
      <mass value="0.0001" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.05" ixy="0.0" ixz="0.0"
               iyy="0.05" iyz="0.0"
               izz="0.05" />
    </inertial>
  </link>
  <joint name="cameraPsi" type="continuous" >
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="head_link" />
      <child link="camera_psi_link" />
      <axis xyz="0 0 1"  rpy="0 0 0"/>
  </joint>

  <link name="camera_theta_link">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <inertial>
      <mass value="0.0001" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.05" ixy="0.0" ixz="0.0"
               iyy="0.05" iyz="0.0"
               izz="0.05" />
    </inertial>
  </link>

  <joint name="cameraTheta" type="continuous" >
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="camera_psi_link"/>
      <child link="camera_theta_link"/>
      <axis xyz="0 1 0"  rpy="0 0 0"/>
  </joint>

  <joint name="cameraPhi" type="continuous" >
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="camera_theta_link"/>
      <child link="camera_link"/>
      <axis xyz="1 0 0"  rpy="0 0 0"/>
  </joint>

  <link name="camera_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://blindbot_description/meshes/sensors/asus_xtion_pro_camera/meshes/asus_xtion_pro_camera.dae" />
      </geometry>
    </visual>

    <!-- This inertial field needs doesn't contain reliable data!! mass value old 0.564 -->
    <inertial>
      <mass value="0.0001" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.05" ixy="0.0" ixz="0.0"
               iyy="0.05" iyz="0.0"
               izz="0.05" />
    </inertial>
  </link>

  <joint name="camera_rgb_joint" type="fixed">
    <origin xyz="${asus_cam_rgb_px} ${asus_cam_rgb_py} ${asus_cam_rgb_pz}" rpy="0 0 0"/>
    <parent link="camera_link"/>
    <child link="camera_rgb_frame"/>
  </joint>
  <link name="camera_rgb_frame"/>

  <joint name="camera_rgb_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
    <parent link="camera_rgb_frame"/>
    <child link="camera_rgb_optical_frame"/>
  </joint>
  <link name="camera_rgb_optical_frame"/>

  <joint name="camera_depth_joint" type="fixed">
    <origin xyz="${asus_cam_rgb_px} ${asus_cam_rgb_py + asus_cam_depth_offset} ${asus_cam_rgb_pz}" rpy="0 0 0"/>
    <parent link="camera_link"/>
    <child link="camera_depth_frame"/>
  </joint>
  <link name="camera_depth_frame"/>

  <joint name="camera_depth_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
    <parent link="camera_depth_frame"/>
    <child link="camera_depth_optical_frame"/>
  </joint>
  <link name="camera_depth_optical_frame"/>


  <!-- I have added a person link/joint to put a model of the human (just visually, no inertias) -->
  <link name="person_link">
    <visual>
     <origin xyz="0 0 0" rpy="0 0 0"/>
     <geometry>
      <mesh filename="package://blindbot_description/meshes/person_standing/meshes/standing.dae" />
     </geometry>
    </visual>
  </link>
  <joint name="person_joint" type="fixed">
    <origin xyz="-0.15 0 0" rpy="0 0 1.57"/>
    <parent link="base_footprint"/>
    <child link="person_link"/>
  </joint>

  <!-- <transmission name="base_to_camera_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <actuator name="motor1">
     <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
     <mechanicalReduction>1</mechanicalReduction>
    </actuator>
    <joint name="camera_joint">
     <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
   </transmission> -->

  <transmission name="base_to_camera_trans1">
    <type>transmission_interface/SimpleTransmission</type>
    <actuator name="motor1">
     <mechanicalReduction>1</mechanicalReduction>
    </actuator>
    <joint name="cameraPsi">
     <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
   </transmission>

   <transmission name="base_to_camera_trans2">
     <type>transmission_interface/SimpleTransmission</type>
     <actuator name="motor2">
      <mechanicalReduction>1</mechanicalReduction>
     </actuator>
     <joint name="cameraTheta">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
     </joint>
    </transmission>

    <transmission name="base_to_camera_trans3">
      <type>transmission_interface/SimpleTransmission</type>
      <actuator name="motor3">
       <mechanicalReduction>1</mechanicalReduction>
      </actuator>
      <joint name="cameraPhi">
       <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
     </transmission>

</robot>
