device:
  N_phosphenes: 1500
  FOV_deg: 11.0
  map_mode: 1 # So the distribution of phosphenes occupies all rectangle area (2 for circle)
  grid_mode: 1
  noise_stddev: 0.0
  dropout_rate: 0.0
  FOV_phosphene_deg: 0.3 # 5-30 min... 0.1ยบ-0.5ยบ
  N_levels: 7
  aspect_ratio: 0.95 #38/40

