axis_linear: 1
scale_linear: 0.6
scale_linear_turbo: 2

axis_angular: 0
scale_angular: 0.8

enable_button: 6  # L2 shoulder button
enable_turbo_button: 4  # L1 shoulder button

head_up_button: 0
head_down_button: 2
reset_button: 7